## **Load Audio file**

In [42]:
import librosa
audio,sr=librosa.load('/content/audiodata.wav')

In [43]:
audio

array([ 5.1159077e-13,  0.0000000e+00, -1.8189894e-12, ...,
       -9.7560813e-04, -9.4943331e-04, -1.0384974e-03], dtype=float32)

In [44]:
sr

22050

## **Resample audio to 44.1 khz**

In [46]:
sr_new = 44100
audio_new = librosa.resample(audio, orig_sr=sr, target_sr=sr_new)
# Pass original and target sampling rates as keyword arguments

## **Noice Reduction**

In [48]:
import noisereduce as nr
audio_reduced=nr.reduce_noise(y=audio_new,sr=sr_new)

## **Normalize amplitde**

In [49]:
import numpy as np

In [50]:
audio_normalised=audio_reduced/np.max(np.abs(audio_reduced))

## **Extract MFCC Features**

In [51]:
mfccs=librosa.feature.mfcc(y=audio_normalised,sr=sr_new,n_mfcc=40)

In [76]:
import pandas as pd
df=pd.DataFrame(mfccs)
df

0           1           2           3           4           5      \
0  -558.806519 -558.806519 -558.806519 -558.806519 -558.806519 -558.806519   
1     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
2     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
3     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
4     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
5     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
6     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
7     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
8     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
9     0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
10    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
11    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
12    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
13    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
14    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
15    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
16    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
17    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
18    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
19    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
20    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
21    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
22    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
23    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
24    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
26    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
27    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
28    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
29    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
30    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
31    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
32    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
33    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
34    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
35    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
36    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
37    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
38    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
39    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   

         6           7           8           9      ...       16886  \
0  -558.806519 -558.806519 -558.806519 -558.806519  ... -558.806519   
1     0.000000    0.000000    0.000000    0.000000  ...    0.000000   
2     0.000000    0.000000    0.000000    0.000000  ...    0.000000   
3     0.000000    0.000000    0.000000    0.000000  ...    0.000000   
4     0.000000    0.000000    0.000000    0.000000  ...    0.000000   
5     0.000000    0.000000    0.000000    0.000000  ...    0.000000   
6     0.000000    0.000000    0.000000    0.000000  ...    0.000000   
7     0.000000    0.000000    0.000000    0.000000  ...    0.000000   
8     0.000000    0.000000    0.000000    0.000000  ...    0.000000   
9     0.000000    0.000000    0.000000    0.000000  ...    0.000000   
10    0.000000    0.000000   

from matplotlib import pyplot as plt
df[0].plot(kind='hist', bins=20, title=0)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df[1].plot(kind='hist', bins=20, title=1)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df[2].plot(kind='hist', bins=20, title=2)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df[3].plot(kind='hist', bins=20, title=3)
plt.gca().spines[['top', 'right',]].set_visible(False)

/usr/local/lib/python3.10/dist-packages/matplotlib/collections.py:963: RuntimeWarning: invalid value encountered in sqrt
  scale = np.sqrt(self._sizes) * dpi / 72.0 * self._factor


from matplotlib import pyplot as plt
df.plot(kind='scatter', x=0, y=1, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

/usr/local/lib/python3.10/dist-packages/matplotlib/collections.py:963: RuntimeWarning: invalid value encountered in sqrt
  scale = np.sqrt(self._sizes) * dpi / 72.0 * self._factor


from matplotlib import pyplot as plt
df.plot(kind='scatter', x=1, y=2, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

/usr/local/lib/python3.10/dist-packages/matplotlib/collections.py:963: RuntimeWarning: invalid value encountered in sqrt
  scale = np.sqrt(self._sizes) * dpi / 72.0 * self._factor


from matplotlib import pyplot as plt
df.plot(kind='scatter', x=2, y=3, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

/usr/local/lib/python3.10/dist-packages/matplotlib/collections.py:963: RuntimeWarning: invalid value encountered in sqrt
  scale = np.sqrt(self._sizes) * dpi / 72.0 * self._factor


from matplotlib import pyplot as plt
df.plot(kind='scatter', x=3, y=4, s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series[0]
  ys = series[227]
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values(0, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(0)
_ = plt.ylabel(227)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series[0]
  ys = series[228]
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values(0, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(0)
_ = plt.ylabel(228)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series[0]
  ys = series[229]
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values(0, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(0)
_ = plt.ylabel(229)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series[0]
  ys = series[230]
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = df.sort_values(0, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(0)
_ = plt.ylabel(230)

from matplotlib import pyplot as plt
df[0].plot(kind='line', figsize=(8, 4), title=0)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df[1].plot(kind='line', figsize=(8, 4), title=1)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df[2].plot(kind='line', figsize=(8, 4), title=2)
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
df[3].plot(kind='line', figsize=(8, 4), title=3)
plt.gca().spines[['top', 'right']].set_visible(False)

## **Split the data into traing and testing sets**




In [69]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(mfccs.T, labels, train_size=0.80, random_state=42)

In [70]:
y_train

array([0., 0., 0., ..., 0., 0., 0.])

## **Choosing model**

In [74]:
# ... (Your existing code for loading audio and extracting features) ...

# 1. Check Label Distribution:
print("Label Distribution:", np.unique(labels, return_counts=True))

# 2. Example of Examining Individual Files:
for i in range(min(10, len(audio_new))): # Examine first 10 files (or fewer)
    print(f"File: {audio_new[i]}, Label: {labels[i]}")

# 3. If using a label encoder, double-check its mapping
# ... (your label encoding code) ...
# print("Label Encoder Classes:", encoder.classes_)

# 4. Carefully review your data loading process, including:
#    - Directory structure of your audio files
#    - Logic for assigning labels
#    - Filtering or subsetting operations

# ... (Apply corrections based on your investigation) ...

Label Distribution: (array([0.]), array([16896]))
File: 1.9610979506978765e-12, Label: 0.0
File: 4.547473508864641e-13, Label: 0.0
File: 2.7284841053187847e-12, Label: 0.0
File: 9.094947017729282e-13, Label: 0.0
File: 0.0, Label: 0.0
File: -4.774847184307873e-12, Label: 0.0
File: -1.8189894035458565e-12, Label: 0.0
File: -4.547473508864641e-12, Label: 0.0
File: -1.8189894035458565e-12, Label: 0.0
File: -4.320099833421409e-12, Label: 0.0


In [78]:
import numpy as np
import librosa
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# ... (Your existing code for loading audio and extracting features) ...

# Assuming your labels variable is named 'labels'
unique_classes = np.unique(labels)

# Check if only one class is present
if len(unique_classes) < 2:
    print("Error: y_train contains only one class. Check your data and preprocessing.")
    print("Generating synthetic data for the second class")

    # Generating synthetic data for the second class
    # Example: Adding random noise to create variations in the existing data
    num_synthetic_samples = len(mfccs.T) // 2  # Create half the number of original samples
    noise_factor = 0.1  # Adjust the noise factor as needed

    synthetic_data = mfccs.T[:num_synthetic_samples] + noise_factor * np.random.randn(*mfccs.T[:num_synthetic_samples].shape)
    synthetic_labels = np.ones(num_synthetic_samples)  # Assigning label '1' to synthetic data

    # Concatenate the synthetic data with the original data
    mfccs_combined = np.concatenate([mfccs.T, synthetic_data])
    labels_combined = np.concatenate([labels, synthetic_labels])

    # Now use the combined data for train-test split
    x_train, x_test, y_train, y_test = train_test_split(mfccs_combined, labels_combined, test_size=0.2, random_state=42)
else:
    # Proceed with model training
    x_train, x_test, y_train, y_test = train_test_split(mfccs.T, labels, test_size=0.2, random_state=42)

# Training the SVM model
model = SVC(kernel='rbf')
model.fit(x_train, y_train)

Error: y_train contains only one class. Check your data and preprocessing.
Generating synthetic data for the second class


SVC()

# **Model Evaluation**

In [80]:
model.predict(x_test)

array([0., 0., 0., ..., 0., 0., 0.])

In [81]:
model.score(x_test,y_test)

0.6742947326888933

In [84]:
model.score(x_train,y_train)

0.6647595561035758

In [87]:
data_new = x_train[:1]

In [88]:
model.predict(data_new)

array([0.])

In [89]:
y_train[:1]

array([1.])